title: KaijuSwap
description: Welcome to KaijuSwap
url: https://nicolas-martin.github.io
baseurl: "/kaijuswap.github.io"

plugins:
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

permalink: pretty